# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pushup_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(980, 838)
        Frame.setMinimumSize(QtCore.QSize(980, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/首页.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Frame.setWindowIcon(icon)
        Frame.setStyleSheet("QPushButton#close_pushButton{\n"
" background-color: #ce5137;\n"
" border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#close_pushButton:hover{\n"
" background-size: cover;\n"
" background-image: url(:/icon/icon/close.svg);\n"
"}\n"
"\n"
"QPushButton#min_pushButton{\n"
" background-color: #a1c661;\n"
" border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#min_pushButton:hover{\n"
" background-size: cover;\n"
" background-image: url(:/icon/icon/minimize.svg);\n"
"}\n"
"\n"
"QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0.0284091 rgba(129, 255, 251, 255), stop:0.9375 rgba(255, 255, 255, 255));\n"
"\n"
"border-radius: 14;\n"
"}\n"
"\n"
"QTableWidget, QTableView\n"
"{\n"
"    gridline-color: #999999;    /*表格中的网格线条颜色*/\n"
"    background: #FDFDFD;\n"
"    /*设置交替颜色，需要在函数属性中设置:tableWidget->setAlternatingRowColors(true)*/\n"
"    alternate-background-color: #EEEEEF;\n"
"    /*selection-color:#FDFDFD;    鼠标选中时前景色：文字颜色*/\n"
"    selection-background-color:#8BF;   /*鼠标选中时背景色*/\n"
"    border:1px solid #999999;  /*边框线的宽度、颜色*/\n"
"    /*border:none;    去除边界线*/\n"
"    /*border-radius:5px;*/\n"
"    /*padding:10px 10px;*/  /*表格与边框的间距*/\n"
"}\n"
"QTableView::item, QTabWidget::item{\n"
"    background: transparent;\n"
"    outline-style: none;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableView::item:hover {\n"
"    background: #8BF;\n"
"    border: 1px solid #EA2;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background: #8BF;\n"
"    color: #EEEEEF;\n"
"}\n"
"\n"
"QTableView::item:selected:active {\n"
"    background: #59F;\n"
"    color: #EEEEEF;\n"
"}\n"
"\n"
"QTableWidget QComboBox{\n"
"    margin: 2px;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"QGroupBox {\n"
"border: 2px solid #999999;\n"
"border-radius: 4px;\n"
"margin-top: 0.5em;\n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top left;\n"
"left: 1em;\n"
"top: 0.1em;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Frame)
        self.widget.setMinimumSize(QtCore.QSize(800, 600))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 961, 196))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(240, 110))
        self.groupBox_4.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.right_label = QtWidgets.QLabel(self.groupBox_4)
        self.right_label.setStyleSheet("font: 18pt \"Arial\";")
        self.right_label.setObjectName("right_label")
        self.horizontalLayout_4.addWidget(self.right_label)
        self.horizontalLayout_6.addWidget(self.groupBox_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit.setStyleSheet("font: 22pt \"Arial\";")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_5.addWidget(self.textEdit)
        self.start_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.start_pushButton.setMinimumSize(QtCore.QSize(130, 45))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.start_pushButton.setFont(font)
        self.start_pushButton.setObjectName("start_pushButton")
        self.horizontalLayout_5.addWidget(self.start_pushButton)
        self.min_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.min_pushButton.setMinimumSize(QtCore.QSize(20, 20))
        self.min_pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.min_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min_pushButton.setText("")
        self.min_pushButton.setObjectName("min_pushButton")
        self.horizontalLayout_5.addWidget(self.min_pushButton)
        self.close_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.close_pushButton.setMinimumSize(QtCore.QSize(20, 20))
        self.close_pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.close_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_pushButton.setText("")
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout_5.addWidget(self.close_pushButton)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.camera_label = QtWidgets.QLabel(self.widget)
        self.camera_label.setGeometry(QtCore.QRect(258, 190, 761, 600))
        self.camera_label.setMinimumSize(QtCore.QSize(600, 600))
        self.camera_label.setText("")
        self.camera_label.setObjectName("camera_label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setGeometry(QtCore.QRect(1, 201, 240, 200))
        self.groupBox_3.setMinimumSize(QtCore.QSize(240, 200))
        self.groupBox_3.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.suggest_label = QtWidgets.QLabel(self.groupBox_3)
        self.suggest_label.setStyleSheet("font: 12pt \"Arial\";")
        self.suggest_label.setObjectName("suggest_label")
        self.horizontalLayout_7.addWidget(self.suggest_label)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 400, 240, 400))
        self.groupBox_2.setMinimumSize(QtCore.QSize(240, 400))
        self.groupBox_2.setMaximumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.wrong_label = QtWidgets.QLabel(self.groupBox_2)
        self.wrong_label.setStyleSheet("font: 24pt \"Arial\";")
        self.wrong_label.setObjectName("wrong_label")
        self.horizontalLayout_3.addWidget(self.wrong_label)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Pushup"))
        self.groupBox_4.setTitle(_translate("Frame", "Correct"))
        self.right_label.setText(_translate("Frame", "Right number"))
        self.label.setText(_translate("Frame", "Pushup"))
        self.textEdit.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:22pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'Segoe UI\',\'system-ui\',\'Apple Color Emoji\',\'Segoe UI Emoji\',\'Segoe UI Web\',\'sans-serif\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'Segoe UI\',\'system-ui\',\'Apple Color Emoji\',\'Segoe UI Emoji\',\'Segoe UI Web\',\'sans-serif\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'Segoe UI\',\'system-ui\',\'Apple Color Emoji\',\'Segoe UI Emoji\',\'Segoe UI Web\',\'sans-serif\'; font-size:24pt;\">Target Reps</span></p></body></html>"))
        self.start_pushButton.setText(_translate("Frame", "Start"))
        self.groupBox_3.setTitle(_translate("Frame", "Coach Suggest"))
        self.suggest_label.setText(_translate("Frame", "Suggest information"))
        self.groupBox_2.setTitle(_translate("Frame", "Wrong"))
        self.wrong_label.setText(_translate("Frame", "Wrong number"))
from res import app_rc